### ISSUE TITLE
Multiple widgets used the same GlobalKey

### ISSUE THREAD

**Issue by DannieKr** [Rexo99/MoneyMate#32]
* Exception keeps popping up
![grafik](https://github.com/Rexo99/MoneyMate/assets/72869131/8f1f81b4-5ddc-4eb2-bd52-ef7e93b4158f)

**Comment by DoriZim** [comment]
Exception kann provoziert werden, indem das Theme geändert wird, oder eine andere Page geöffnet wird, sodass sich die HUD updaten muss. Da die Keys der Widgets darin aber im MyAppState definiert werden, updaten sich die Keys nicht und die alten Keys werden mehrfach verwendet.

Hilfreichere Fehlermmeldung:

Duplicate GlobalKeys detected in widget tree.

The following GlobalKeys were specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The keys were:
- [GlobalKey#80783]
  [GlobalKey#eb773]
  [GlobalKey#5e303]
This was determined by noticing that after widgets with the above global keys were moved out of their respective previous parents, those previous parents never updated during this frame, meaning that they either did not update at all or updated before the widgets were moved, in either case implying that they still think that they should have a child with those global keys.
The specific parents that did not update after having one or more children forcibly removed due to GlobalKey reparenting are:
- IconTheme(size: 24.0, color: Color(0xff6750a4))
  IconTheme(size: 24.0, color: MaterialColor(primary value: Color(0xff9e9e9e)))

**Comment by DoriZim** [comment]
Closed unter Vorbehalt
